# Generated by Django 4.2.5 on 2023-09-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_description_product_synopsis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='synopsis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='director',
        ),
    ]
